IT-Store/Controllers/Account/AddressesController.cs
using IT_Store.Models;
using IT_Store.Repositories.Interfaces;
using IT_Store.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace IT_Store.Controllers.Account
{
    [Authorize(Roles = "User")]
    [Route("Account/{controller}/{action=Index}/{id?}")]
    public class AddressesController : Controller
    {
        private readonly IAddressRepository _addressRep;

        public AddressesController(IAddressRepository addressRep)
        {
            _addressRep = addressRep;
        }
        [HttpGet]
        public IActionResult Index()
        {
            return View(_addressRep.GetByUserId(this.GetUserId()));
        }
        [HttpGet]
        public IActionResult Add()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Add(ViewModel_AddAddress model)
        {
            if (ModelState.IsValid) { 
                Address address=model.CreateAddress(this.GetUserId());
                _addressRep.Add(address);
                _addressRep.Save();
                return RedirectToAction("Index");
            }
            return View();
        }
        [HttpGet]
        public IActionResult Delete(int id)
        {
            try
            {
                _addressRep.Delete(id);
                _addressRep.Save();
            }
            catch (Exception)
            {
                ModelState.AddModelError("", "Failed to delete the address");
            }
            return RedirectToAction("Index");
        }
    }
}

IT-Store/Views/Addresses/Add.cshtml
@model ViewModel_AddAddress
@{
	ViewBag.Title = "Add Address";
}

<div class="row" style="display: flex;flex-direction: column;align-items: center; margin:40px 0;">
<h4>Add Address</h4>
    <div class="col-md-4">
        <form asp-action="Add">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <div class="form-group my-4">
                <label asp-for="AddressLine" class="control-label"></label>
                <input asp-for="AddressLine" class="form-control" />
                <span asp-validation-for="AddressLine" class="text-danger"></span>
            </div>
            <div class="form-group my-4">
                <label asp-for="City" class="control-label"></label>
                <input asp-for="City" class="form-control" />
                <span asp-validation-for="City" class="text-danger"></span>
            </div>
            <div class="form-group my-4">
                <label asp-for="Country" class="control-label"></label>
                <input asp-for="Country" class="form-control" />
                <span asp-validation-for="Country" class="text-danger"></span>
            </div>
            <div class="form-group my-4">
                <label asp-for="PhoneNumber" class="control-label"></label>
                <input asp-for="PhoneNumber" class="form-control" />
                <span asp-validation-for="PhoneNumber" class="text-danger"></span>
            </div>
            <div class="form-group my-4">
                <label asp-for="Landmark" class="control-label"></label>
                <input asp-for="Landmark" class="form-control" />
                <span asp-validation-for="Landmark" class="text-danger"></span>
            </div>
            
            <div class="form-group my-4">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>

            <div>
                <a asp-action="Index">Back to List</a>
            </div>

        </form>
    </div>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

IT-Store/Views/Addresses/Index.cshtml
@model IEnumerable<Address>
@{
	ViewBag.Title = "User Addresses";
}


<div class="" style="display: flex;flex-direction: column;align-items: center; margin:40px 0;">
 <a asp-action="Add" asp-controller="Addresses" class=" m-3 btn bg-primary text-white">Add new address</a>
 	<div class="col-12 col-lg-8 col-xxl-12 d-flex">
 		<div class="card flex-fill">
 			<div class="card-header">

 				<h5 class="card-title mb-0">Your Addresses</h5>
 			</div>
 			<table class="table table-hover my-0">
 				<thead>
 					<tr>
 						<th>@Html.DisplayNameFor(model => model.AddressId)</th>
 						<th class="d-none d-xl-table-cell">@Html.DisplayNameFor(model => model.AddressLine)</th>
 						<th class="d-none d-xl-table-cell">@Html.DisplayNameFor(model => model.PhoneNumber)</th>
 						<th class="d-none d-md-table-cell"></th>
 					</tr>
 				</thead>
 				<tbody>
 					@foreach (var item in Model)
 					{
 						<tr>
 							<td class="d-none d-xl-table-cell">@Html.DisplayFor(modelItem => item.AddressId)</td>
                            <td>@Html.DisplayFor(modelItem => item.AddressLine)</td>
                            <td class="d-none d-xl-table-cell">@Html.DisplayFor(modelItem => item.PhoneNumber)</td>
 							<td class="d-none d-xl-table-cell">
                                <a asp-action="Edit" asp-route-id="@item.AddressId" asp-controller="Addresses" class="btn text-white bg-secondary">
 									<i class="align-middle" data-feather="edit"></i> <span class="align-middle">Edit</span>
 								</a>
                                <a asp-action="Delete" asp-controller="Addresses" asp-route-id="@item.AddressId" class="btn text-white bg-danger">
 									<i class="align-middle" data-feather="delete"></i> <span class="align-middle">Delete</span>
 								</a>

 							</td>
 						</tr>
 					}
 				</tbody>
 			</table>
 		</div>
 	</div>
</div>