IT-Store/Models/Brand.cs
using System.ComponentModel.DataAnnotations;

namespace IT_Store.Models;

public partial class Brand
{
    public int BrandId { get; set; }

    public string Name { get; set; } = null!;

    public string? Description { get; set; }
    [Display(Name ="Created at")]
    public DateTime CreatedAt { get; set; }

    public DateTime? DeletedAt { get; set; }

    public bool Isdeleted { get; set; }

    public virtual ICollection<Product> Products { get; set; } = new List<Product>();
}

IT-Store/Controllers/Admin/BrandsController.cs
using IT_Store.Models;
using IT_Store.Repositories.Interfaces;
using IT_Store.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace IT_Store.Controllers.Admin
{
	[Route("Admin/{controller}/{action=Index}/{id?}")]
	[Authorize(Roles ="Admin")]
	public class BrandsController : Controller
	{
		private readonly IBrandRepository _repository;

		public BrandsController(IBrandRepository repository)
		{
			_repository = repository;
		}

		public IActionResult Index()
		{
			TempData["AdminTabs"] = AdminTabs.Brands.ToString();
			return View("~/Views/Admin/Brands/Index.cshtml",_repository.GetAll());
		}
		[HttpGet]
		public IActionResult Add()
		{
			return View("~/Views/Admin/Brands/Add.cshtml");
		}
		[HttpPost]
        public IActionResult Add(ViewModel_AddBrand model)
        {
			if (ModelState.IsValid) {
				try
				{
					var brand=model.Brand;
					_repository.Add(brand);
					_repository.Save();
					return RedirectToAction("Index");
				}
				catch (Exception ex)
				{
					ModelState.AddModelError("Name",ex.Message);
				}
			}
            return View("~/Views/Admin/Brands/Add.cshtml");
        }
		[HttpGet]
		public IActionResult Details(int id) {
			return View("~/Views/Admin/Brands/Details.cshtml",_repository.GetById(id));
		}
		[HttpGet]
		public IActionResult Edit(int id) { 
			return View("~/Views/Admin/Brands/Edit.cshtml",_repository.GetById(id));
		}
		[HttpPost]
		public IActionResult Edit(Brand brand)
		{
			if (ModelState.IsValid)
			{
				try
				{
					_repository.Update(brand);
					_repository.Save();
					return RedirectToAction("Details", new {id=brand.BrandId});
				}
				catch (Exception ex)
				{
					ModelState.AddModelError("", ex.Message);
				}
			}
			return Edit(brand.BrandId);
		}
		[HttpGet]
		public IActionResult Delete(int id) {
			try
			{
				_repository.Delete(id);
				_repository.Save();
			}
			catch (Exception)
			{
				ModelState.AddModelError("", "Failed to delete the brand");
			}
			return RedirectToAction("Index");
		}
    }
}

IT-Store/Views/Admin/Brands/Add.cshtml
@model ViewModel_AddBrand

@{
    ViewData["Title"] = "Add Brand";
    Layout = "~/Views/Shared/_Admin-Layout.cshtml";
}
<h4>Add Brand</h4>
<div class="row">
    <div class="col-md-4">
        <form asp-action="Add">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group my-4">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group my-4">
                <label asp-for="Description" class="control-label"></label>
                <textarea asp-for="Description" class="form-control" ></textarea>
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group my-4">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

IT-Store/Views/Admin/Brands/Details.cshtml
@model Brand
@{
    ViewData["Title"] = "Brand Details";
    Layout = "~/Views/Shared/_Admin-Layout.cshtml";
}



<h4>Brand Details</h4>
<div>
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CreatedAt)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CreatedAt)
        </dd>
    </dl>
</div>
<div>
    <a class="btn text-white bg-secondary" asp-action="Edit" asp-controller="Brands" asp-route-id="@Model.BrandId">
        <i class="align-middle" data-feather="edit"></i> <span class="align-middle">Edit</span>
    </a>
    <a class="btn text-white bg-danger" asp-action="Delete" asp-controller="Brands" asp-route-id="@Model.BrandId">
        <i class="align-middle" data-feather="delete"></i> <span class="align-middle">Delete</span>
    </a>
    <a asp-action="Index" class=" py-4">Back to List</a>
</div>

IT-Store/Views/Admin/Brands/Edit.cshtml
@model Brand

@{
    ViewData["Title"] = "Edit Brand";
    Layout = "~/Views/Shared/_Admin-Layout.cshtml";
}

<h4>Edit Brand</h4>

<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="BrandId" />
            <input type="hidden" asp-for="CreatedAt" />
            <div class="form-group">
                <label asp-for="Name" class="control-label my-2"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
           
            <div class="form-group my-4">
                <label asp-for="Description" class="control-label my-2"></label>
                <textarea asp-for="Description" class="form-control" style="height:140px"></textarea>
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group my-4">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

IT-Store/Views/Admin/Brands/Index.cshtml
@model IEnumerable<Brand>
@{
    ViewData["Title"] = "Brands";
    Layout = "~/Views/Shared/_Admin-Layout.cshtml";
}

<a class=" m-3 btn bg-primary text-white" asp-action="Add" asp-asp-controller="Brands">Add Brand</a>

<div class="row">
	<div class="col-12 col-lg-8 col-xxl-12 d-flex">
		<div class="card flex-fill">
			<div class="card-header">

				<h5 class="card-title mb-0">Brands</h5>
			</div>
			<table class="table table-hover my-0">
				<thead>
					<tr>
						<th>@Html.DisplayNameFor(model=>model.Name)</th>
						<th class="d-none d-xl-table-cell">@Html.DisplayNameFor(model => model.CreatedAt)</th>
						<th class="d-none d-md-table-cell"></th>
					</tr>
				</thead>
				<tbody>
					@foreach (var item in Model)
					{
						<tr>
							<td>@Html.DisplayFor(modelItem=>item.Name)</td>
							<td class="d-none d-xl-table-cell">@Html.DisplayFor(modelItem=>item.CreatedAt)</td>
							<td class="d-none d-xl-table-cell">
								<a class="btn text-white bg-primary" asp-action="Details" asp-controller="Brands" asp-route-id="@item.BrandId">
									<i class="align-middle" data-feather="info"></i> <span class="align-middle">Details</span>
								</a>
								<a class="btn text-white bg-secondary" asp-action="Edit" asp-controller="Brands" asp-route-id="@item.BrandId">
									<i class="align-middle" data-feather="edit"></i> <span class="align-middle">Edit</span>
								</a>
								<a class="btn text-white bg-danger" asp-action="Delete" asp-controller="Brands" asp-route-id="@item.BrandId">
									<i class="align-middle" data-feather="delete"></i> <span class="align-middle">Delete</span>
								</a>
							</td>
						</tr>	
					}
				</tbody>
			</table>
		</div>
	</div>
</div>